// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';
import {main} from '../models';

export function Analyze(arg1:number):Promise<internal.AnalysisResult>;

export function AnalyzeLib(arg1:number):Promise<internal.AnalysisResult>;

export function ApplyFilters(arg1:number):Promise<Record<string, main.FilterResult>>;

export function ExportFilterResults(arg1:number):Promise<Record<string, string>>;
