// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1) {
  return window['go']['main']['App']['Analyze'](arg1);
}

export function AnalyzeLib(arg1) {
  return window['go']['main']['App']['AnalyzeLib'](arg1);
}

export function ApplyFilters(arg1) {
  return window['go']['main']['App']['ApplyFilters'](arg1);
}

export function ExportFilterResults(arg1) {
  return window['go']['main']['App']['ExportFilterResults'](arg1);
}
