// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function Analyze():Promise<internal.AnalysisResult>;

export function Greet(arg1:string):Promise<string>;
