// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze() {
  return window['go']['main']['App']['Analyze']();
}

export function AnalyzeLib() {
  return window['go']['main']['App']['AnalyzeLib']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
